# Generated by Django 3.2.25 on 2024-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('aceptado', 'Pedido aceptado'), ('en_camino', 'En camino'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='espera', max_length=10),
        ),
    ]
