# Generated by Django 3.2.25 on 2024-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp2', '0002_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='dni',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='nombres',
            field=models.CharField(default=9999999999999, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('aceptado', 'Pedido aceptado'), ('en_camino', 'En camino'), ('cancelado', 'Cancelado')], default='espera', max_length=10),
        ),
    ]
