# Generated by Django 3.2.25 on 2024-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp2', '0003_auto_20241026_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionenvio',
            name='codigo_postal',
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='correo',
            field=models.EmailField(default=999999999, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='celular',
            field=models.CharField(default=999999999999999, max_length=15),
            preserve_default=False,
        ),
    ]
