# Generated by Django 3.2.25 on 2024-10-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp2', '0005_rename_provincia_direccionenvio_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pp2.direccionenvio'),
        ),
    ]
